# noise/_config.yml
# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives

social:
  email: mingyi.me@gmail.com
  github: https://github.com/liangmingyi
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: mingyi-me
disqus: #disqus _shortname
google_analytics: #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code

less:
  paths:
    - source/css
  compress:
    true
