slogan: "茗一的笔记."

theme: cerulean
inverse: inverse

menu:
  - title: 文章归档
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: 给我留言
    url: message
    intro: "All the tags."
    icon: "fa fa-pencil"
  - title: 关于本站
    url: about
    intro: "About me."
    icon: "fa fa-info-circle"

links:
  - title: "EI__Nino的专栏"
    url: http://blog.csdn.net/ei__nino
    intro: "VP金."
    icon: "fa fa-share"
  - title: "诚哥的猜想"
    url: http://leechan.me/
    intro: "诚哥"
    icon: "fa fa-github"

widgets:
- search
- broadcast
- category
- tagcloud
- links
- recent_comments
- recent_visitor

rss: 
fancybox: true
favicon: favicon.ico
duoshuo_shortname: mingyi-me

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
swiftype_key: YYG5W2xNQTns7U8J3YqW

# share widgets
bdshare: false
jiathis: true

